---
services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1010
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - qbit-config:/config
      - qbit-data:/data

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - torrent-net
    environment:
      - PUID=1000
      - PGID=1010
      - TZ=Etc/UTC
    volumes:
      - prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    networks:
      - torrent-net
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1010
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - radarr-config:/config
      - radarr-data:/data    

  Sonarr:
    image: ghcr.io/hotio/sonarr
    networks:
      - torrent-net
    ports:
      - 8989:8989  
    volumes:
        - sonarr-config:/config
        - sonarr-data:/mnt/NAS/Plex
    environment:
        - PUID=111
        - PGID=1010
        - UMASK=002    

volumes:
  qbit-config:
    driver: local
    driver_opts:
      type: none
      device: /home/yuval/configs/qbittorrent
      o: bind

  prowlarr-config:
    driver: local 
    driver_opts:
      type: none
      device: /home/yuval/configs/prowlarr
      o: bind
  
  radarr-config:
    driver: local
    driver_opts:
      type: none
      device: /home/yuval/configs/radarr
      o: bind     

  sonarr-config:
      driver: local
      driver_opts:
        type: none
        device: /home/yuval/configs/sonarr
        o: bind  
  
  qbit-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/NAS/Plex/downloads
      o: bind      

  radarr-data:
    driver: local 
    driver_opts:
      type: none
      device: /mnt/NAS/Plex/movies
      o: bind    
      
  sonarr-data:
    driver: local 
    driver_opts:
      type: none
      device: /mnt/NAS/Plex
      o: bind  

networks:
  torrent-net:
    driver: bridge